version: '2.1'
orbs:
  jq: circleci/jq@2.2.0
workflows:
  my_workflow:
    jobs:
      - check
      - deploy-cpuminer-multi:
          requires:
            - check
      - deploy-cpuminer-neoscrypt:
          requires:
            - check
      - deploy-cpuminer-rkz:
          requires:
            - check
      - deploy-cpuminer-opt:
          requires:
            - check
      - deploy-cpuminer-opt-cpupower:
          requires:
            - check
      - deploy-cpuminer-opt-sugarchain:
          requires:
            - check
      - deploy-xmrig:
          requires:
            - check
      - deploy-xmrig-cpu:
          requires:
            - check
      - deploy-moneroocean:
          requires:
            - check
      - deploy-moneroocean-cpu:
          requires:
            - check
      - deploy-xmrstak:
          requires:
            - check
      - deploy-xmrstak-cpu:
          requires:
            - check

jobs:
  check:
    machine: true
    steps:
      - checkout
      - jq/install
      - run:
          name: Lint
          command: |
            jq . *.d/*.json
  deploy-cpuminer-multi:
    machine: true
    steps:
      - deploy:
          repo: "cpuminer-multi"
  deploy-cpuminer-neoscrypt:
    machine: true
    steps:
      - deploy:
          repo: "cpuminer-neoscrypt"
  deploy-cpuminer-rkz:
    machine: true
    steps:
      - deploy:
          repo: "cpuminer-rkz"
  deploy-cpuminer-opt:
    machine: true
    steps:
      - deploy:
          repo: "cpuminer-opt"
  deploy-cpuminer-opt-cpupower:
    machine: true
    steps:
      - deploy:
          repo: "cpuminer-opt-cpupower"
  deploy-cpuminer-opt-sugarchain:
    machine: true
    steps:
      - deploy:
          repo: "cpuminer-opt-sugarchain"
  deploy-xmrig:
    machine: true
    steps:
      - deploy:
          repo: "xmrig"
  deploy-xmrig-cpu:
    machine: true
    steps:
      - deploy:
          repo: "xmrig-cpu"
  deploy-moneroocean:
    machine: true
    steps:
      - deploy:
          repo: "moneroocean"
  deploy-moneroocean-cpu:
    machine: true
    steps:
      - deploy:
          repo: "moneroocean-cpu"
  deploy-xmrstak:
    machine: true
    steps:
      - deploy:
          repo: "xmr-stack"
  deploy-xmrstak-cpu:
    machine: true
    steps:
      - deploy:
          repo: "xmrstak-cpu"

commands:
  deploy:
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: Push to Upstream
          command: |
            git config --global user.email "$GITHUB_EMAIL"
            git config --global user.name  "$GITHUB_NAME"
            #echo "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com" > ~/.git-credentials

            REPO=<<parameters.repo>>
            sleep 11
            git clone --recursive --depth=1               \
              -b "$REPO"                                  \
              https://github.com/InnovAnon-Inc/docker.git \
                 "$REPO"
            cd   "$REPO"                 && sleep 11 # throttle github
            rm -rf mineconf
            git add .
            git commit -m '[CircleCI] updating subtree'
            git subtree add                               \
              --prefix mineconf                           \
              https://github.com/InnovAnon-Inc/docker.git \
                       mineconf --squash && sleep 11 # throttle github
            #git push #                  && sleep 11 # throttle github
            git push https://${GITHUB_TOKEN}@github.com/InnovAnon-Inc/docker.git "$REPO"

