version: 2.1

commands:
  build:
    parameters:
      coin:
        # TODO
        default: "yespower"
        type: string
      docker_tag:
        default: "native"
        type: string
    steps:
      - checkout
      #- setup_remote_docker
      #- restore_cache:
      #    keys:
      #      - v1-{{ .Branch }}
      #    paths:
      #      - /caches/app.tar
      #- run:
      #    name: Load Docker image layer cache
      #    command: |
      #      docker load -i /caches/app.tar | :
      - run:
          name: Build
          command: |
            COIN=<<parameters.coin>>
            DOCKER_TAG=<<parameters.docker_tag>>
            docker build                           \
              -t innovanon/cpuminer-multi:$DOCKER_TAG       \
              --build-arg DOCKER_TAG="$DOCKER_TAG" \
              --build-arg COIN="$COIN"             \
              --pull .
      #- run:
      #    name: Save Docker image layer cache
      #    command: |
      #      mkdir -p /caches
      #      docker save -o /caches/app.tar app
      #- save_cache:
      #    key: v1-{{ .Branch }}-{{ epoch }}
      #    paths:
      #      - /caches/app.tar
      - run:
          name: Test
          command: |
            DOCKER_TAG=<<parameters.docker_tag>>
            [[ "$DOCKER_TAG" = native  ]] ||
            [[ "$DOCKER_TAG" = generic ]] ||
            exit 0

            CID="`docker run -d --rm innovanon/cpuminer-multi:$DOCKER_TAG`"
            echo "CID=$CID"

            docker ps -a | grep "${CID::12}"
            #sleep 99
            sleep 19
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            docker ps -a | grep "${CID::12}"

            # TODO trigger dockerhub, don't build automatically
            echo TODO trigger dockerhub

            docker stop "$CID"

jobs:
  build-multi:
    machine: true
      #docker_layer_caching: true
    steps:
      - build
  build-multi-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          docker_tag: "generic"
      # TODO push to dockerhub

workflows:
  build-multi:
    jobs:
      - build-multi
      - build-multi-generic

